### ISSUE TITLE
Generals server (System.Net.Sockets.SocketException (97): Address family not supported by protocol)

### ISSUE THREAD

**Issue by roysbike** [MustaphaTR/Generals-Alpha#53]
I try run general server on ubuntu 22.04

`sudo strace ./GeneralsAlpha_64.AppImage --server Server.Name="AM2-Generals" Server.ListenPort=1234 Server.BindAddress="0.0.0.0" Server.AdvertiseOnline=True Server.EnableSingleplayer=true
`

```
wait4(-1, [2024-11-09T18:53:50] Starting dedicated server for mod: gen
Unhandled exception. System.Net.Sockets.SocketException (97): Address family not supported by protocol
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.TcpListener..ctor(IPEndPoint localEP)
   at OpenRA.Server.Server..ctor(List`1 endpoints, ServerSettings settings, ModData modData, ServerType type) in /home/runner/work/Generals-Alpha/Generals-Alpha/engine/OpenRA.Game/Server/Server.cs:line 246
   at OpenRA.Server.Program.Run(String[] args) in /home/runner/work/Generals-Alpha/Generals-Alpha/engine/OpenRA.Server/Program.cs:line 100
   at OpenRA.Server.Program.Main(String[] args) in /home/runner/work/Generals-Alpha/Generals-Alpha/engine/OpenRA.Server/Program.cs:line 28
Aborted
[{WIFEXITED(s) && WEXITSTATUS(s) == 134}], 0, NULL) = 13382
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13382, si_uid=0, si_status=134, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 13382
wait4(-1, 0x7ffcf303c7cc, WNOHANG, NULL) = -1 ECHILD (No child processes)
exit_group(134)                         = ?
+++ exited with 134 +++

```

**Comment by roysbike** [comment]
How to correctly start the general server on Linux?
